@startuml

namespace Figure {
    abstract class BaseFigure {
    }
    namespace Impl {
        class Line {
            +void Intialize(Point start, Point end, GameObject line)
        }
        class Polygon {
        }
        class Solid {
        }
        Line --u|> Figure.BaseFigure
        Line ..u> Figure.Point
        Polygon --u|> Figure.BaseFigure
        Solid --u|> Figure.BaseFigure
    }

    class Point {
        +IReadOnlyReactiveProperty<Vector3> Position
        +void SetPosition(Vector3 position)
    }
    
    Point --u|> UserOperation.IManipulationHandler
    Point --l* BaseFigure
    BaseFigure --u|> UserOperation.IDeletable
}

namespace AppManager {
    class AppStateManager {
        +AppStateReactiveProperty CurrentState
    }

    enum AppState {
        Intialize
        Line
        Polygon
        Solid
    }
    AppStateManager --u> AppState
}

namespace Sizer {
    class LineSizer {
    }
    class PolygonSizer {
    }
    class SolidSizer {
    }

    LineSizer --r|> UserOperation.IPointSettable
    LineSizer --> Figure.Impl.Line
}

namespace UserOperation {
    class VoiceCommandExecutor {
    }
    class PointSetExecutor {
    }

    interface IPointSettable {
        void SetPoint(GameObject prefab, Vector3 position)
    }
    interface IDeletable {
        void DeleteFigure()
    }

    interface IInputClickHandler<<MRTK>>{
    }
    interface IManipulationHandler<<MRTK>>{
    }

    VoiceCommandExecutor --d> IDeletable
    PointSetExecutor --d> IPointSettable
    PointSetExecutor --|> IInputClickHandler

    PointSetExecutor ..> AppManager.AppStateManager

    IInputClickHandler -[hidden]d- IManipulationHandler

    namespace Menu {
        class MenuPresenter {
        }
        class MenuButton {
        }

        MenuPresenter --> MenuButton
        MenuPresenter --u> AppManager.AppStateManager
    }
}

@enduml